services:
  jitsi-web:
    image: jitsi/web:stable-9220
    restart: unless-stopped
    environment:
      - PUBLIC_URL=https://meet.suitit.tech
      - DISABLE_HTTPS=1
      - XMPP_SERVER=prosody
      - XMPP_BOSH_URL_BASE=https://meet.suitit.tech
      - JICOFO_AUTH_USER=focus
      - TZ=Europe/Amsterdam
    volumes:
      - jitsi_web_config:/config
    networks:
      proxy-net:
        aliases:
          - jitsi-web
      jitsi-net:

  prosody:
    image: jitsi/prosody:stable-9220
    restart: unless-stopped
    environment:
      - XMPP_DOMAIN=meet.suitit.tech
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - TZ=Europe/Amsterdam
    volumes:
      - prosody_config:/config
    networks:
      proxy-net:
        aliases:
          - prosody
      jitsi-net:

  jicofo:
    image: jitsi/jicofo:stable-9220
    restart: unless-stopped
    environment:
      - XMPP_SERVER=prosody
      - XMPP_DOMAIN=meet.suitit.tech
      - JICOFO_AUTH_USER=focus
      - JICOFO_AUTH_PASSWORD=${JICOFO_AUTH_PASSWORD}
      - TZ=Europe/Amsterdam
    networks:
      - jitsi-net

  jvb:
    image: jitsi/jvb:stable-9220
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
    environment:
      - XMPP_SERVER=prosody
      - XMPP_DOMAIN=meet.suitit.tech
      - JVB_AUTH_USER=jvb
      - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
      - DOCKER_HOST_ADDRESS=${DOCKER_HOST_ADDRESS}
      - TZ=Europe/Amsterdam
    networks:
      - jitsi-net

volumes:
  jitsi_web_config:
  prosody_config:

networks:
  proxy-net:
    external: true
  jitsi-net:
    driver: bridge
