---
- name: Deploy Mailcow Server
  hosts: mailserver
  become: yes
  roles:
    - docker
    - mailcow

- name: Deploy ONLYOFFICE Document Server
  hosts: appserver
  become: yes
  roles:
    - docker
    - onlyoffice
