name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      stack:
        description: "Which stack to destroy?"
        required: true
        type: choice
        options:
          - infra
          - keycloak

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select stack
        run: echo "STACK=${{ github.event.inputs.stack }}" >> $GITHUB_ENV

      - name: Create tfvars file
        run: |
          cat <<EOF > $STACK/terraform.tfvars
          endpoint = "${{ secrets.ENDPOINT }}"
          application_key = "${{ secrets.APPLICATION_KEY }}"
          application_secret = "${{ secrets.APPLICATION_SECRET }}"
          consumer_key = "${{ secrets.CONSUMER_KEY }}"
          ovh_project_id = "${{ secrets.OVH_PROJECT_ID }}"
          region = "${{ secrets.REGION }}"
          os_username = "${{ secrets.OS_USERNAME }}"
          os_password = "${{ secrets.OS_PASSWORD }}"
          os_project_name = "${{ secrets.OS_PROJECT_NAME }}"
          os_project_id = "${{ secrets.OS_PROJECT_ID }}"
          keycloak_admin_user = "${{ secrets.KEYCLOAK_ADMIN_USER }}"
          keycloak_admin_password = "${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}"
          keycloak_hostname = "${{ secrets.KEYCLOAK_HOSTNAME }}"
          keycloak_url = "https://${{ secrets.KEYCLOAK_HOSTNAME }}/"
          domain = "${{ secrets.DOMAIN }}"
          ssh_keypair_name = "${{ secrets.SSH_KEYPAIR_NAME }}"
          EOF

      - name: Export OpenStack credentials
        run: |
          echo "OS_AUTH_URL=${{ secrets.OS_AUTH_URL }}" >> $GITHUB_ENV
          echo "OS_TENANT_ID=${{ secrets.OVH_PROJECT_ID }}" >> $GITHUB_ENV
          echo "OS_TENANT_NAME=${{ secrets.OVH_PROJECT_ID }}" >> $GITHUB_ENV
          echo "OS_USERNAME=${{ secrets.APPLICATION_KEY }}" >> $GITHUB_ENV
          echo "OS_PASSWORD=${{ secrets.APPLICATION_SECRET }}" >> $GITHUB_ENV
          echo "OS_REGION_NAME=${{ secrets.BUCKET_REGION }}" >> $GITHUB_ENV

      - name: Export S3 credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{ secrets.BUCKET_REGION }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.STACK }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.STACK }}
        run: terraform destroy -auto-approve
