name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      stack:
        description: "Which stack to destroy?"
        required: true
        type: choice
        options:
          - infra
          - keycloak

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select stack
        run: echo "STACK=${{ github.event.inputs.stack }}" >> $GITHUB_ENV

      - name: Create tfvars file
        run: |
          cat <<EOF > $STACK/terraform.tfvars
          endpoint = "${{ secrets.ENDPOINT }}"
          application_key = "${{ secrets.APPLICATION_KEY }}"
          application_secret = "${{ secrets.APPLICATION_SECRET }}"
          consumer_key = "${{ secrets.CONSUMER_KEY }}"
          ovh_project_id = "${{ secrets.OVH_PROJECT_ID }}"
          region = "${{ secrets.REGION }}"
          keycloak_admin_user = "${{ secrets.KEYCLOAK_ADMIN_USER }}"
          keycloak_admin_password = "${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}"
          keycloak_hostname = "${{ secrets.KEYCLOAK_HOSTNAME }}"
          keycloak_url = "https://${{ secrets.KEYCLOAK_HOSTNAME }}/"
          domain = "${{ secrets.DOMAIN }}"
          ssh_keypair_name = "${{ secrets.SSH_KEYPAIR_NAME }}"
          admin_ip_whitelist = "${{ secrets.ADMIN_IP_WHITELIST }}"
          EOF

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.STACK }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.STACK }}
        run: terraform destroy -auto-approve
