name: Terraform

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create tfvars file
        run: |
         cat <<EOF > terraform.tfvars
         endpoint = "${{ secrets.ENDPOINT }}"
         application_key = "${{ secrets.APPLICATION_KEY }}"
         application_secret = "${{ secrets.APPLICATION_SECRET }}"
         consumer_key = "${{ secrets.CONSUMER_KEY }}"
         ovh_project_id = "${{ secrets.OVH_PROJECT_ID }}"
         region = "${{ secrets.REGION }}"
         EOF

      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_wrapper: false  

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
